-- Run this once in the new Supabase project's SQL Editor.
-- Create an auth user in Supabase Auth first, then replace USER_UUID below.

create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('admin', 'operator')),
  created_at timestamptz not null default now(),
  unique (user_id, role)
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  price numeric not null default 0,
  images jsonb not null default '[]'::jsonb,
  variants jsonb not null default '[]'::jsonb,
  type text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.shipping_rates (
  wilaya_id integer primary key,
  wilaya text,
  home_delivery numeric not null default 0,
  stop_desk numeric not null default 0
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  name text,
  phone text,
  wilaya text,
  commune text,
  type_livraison text default 'home',
  station_code text,
  product text,
  variable text,
  items jsonb not null default '[]'::jsonb,
  prix_total numeric not null default 0,
  shipping_cost numeric not null default 0,
  status text not null default 'pending',
  from_draft boolean not null default false,
  notes text,
  call_count integer not null default 0,
  created_at timestamptz not null default now(),
  confirmed_at timestamptz,
  tracking_number text,
  shipping_agency text,
  attribution_source text,
  attribution_medium text,
  noest_status integer,
  noest_response jsonb
);

create table if not exists public.order_history (
  id bigint generated by default as identity primary key,
  order_id text not null,
  old_status text,
  new_status text,
  changed_by text,
  tracking_number text,
  event_key text,
  changed_at timestamptz not null default now()
);

create table if not exists public.order_edits (
  id bigint generated by default as identity primary key,
  order_id text not null,
  changed_by text,
  changes jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists orders_tracking_idx on public.orders(tracking_number);
create index if not exists order_history_order_idx on public.order_history(order_id, changed_at desc);

alter table public.user_roles enable row level security;
alter table public.products enable row level security;
alter table public.shipping_rates enable row level security;
alter table public.orders enable row level security;
alter table public.order_history enable row level security;
alter table public.order_edits enable row level security;

create or replace function public.is_operator()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.user_roles where user_id = auth.uid() and role in ('admin','operator')); $$;

drop policy if exists operator_read_roles on public.user_roles;
create policy operator_read_roles on public.user_roles for select to authenticated using (user_id = auth.uid());
drop policy if exists operator_access_products on public.products;
create policy operator_access_products on public.products for all to authenticated using (public.is_operator()) with check (public.is_operator());
drop policy if exists operator_access_shipping_rates on public.shipping_rates;
create policy operator_access_shipping_rates on public.shipping_rates for select to authenticated using (public.is_operator());
drop policy if exists operator_access_orders on public.orders;
create policy operator_access_orders on public.orders for all to authenticated using (public.is_operator()) with check (public.is_operator());
drop policy if exists operator_access_order_history on public.order_history;
create policy operator_access_order_history on public.order_history for all to authenticated using (public.is_operator()) with check (public.is_operator());
drop policy if exists operator_access_order_edits on public.order_edits;
create policy operator_access_order_edits on public.order_edits for all to authenticated using (public.is_operator()) with check (public.is_operator());

-- After creating the operator user in Supabase Auth, run:
-- insert into public.user_roles (user_id, role) values ('USER_UUID_HERE', 'admin');
